(define (domain bikePE)
	(:requirements :strips)
	(:predicates
		(at ?who ?where)
		(space1Able ?where)
		(space2Able ?where)
		(space3Able ?where)
		(space4Able ?where)
		(space5Able ?where)
		(space6Able ?where)
		(adj ?station ?station2)
		(nextTo ?station ?point)
		(ready ?who)
		(have ?who ?what)
		(is-people ?who)
		(is-bike ?what)
		(is-station ?where)
		(is-point ?where)	
	)
	
	(:action take-bike
		:parameters (?who ?where)
		:precondition (and (is-people ?who)
						(at ?who ?where)
						(ready ?who)
						(or(space1Able ?where)
							(space2Able ?where)
							(space3Able ?where)
							(space4Able ?where)
							(space5Able ?where)
							(space6Able ?where)))		
		:effect (and ()
		)				
						
		)
	)
)